name: lovable

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: lovable
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  stripe-cli:
    image: stripe/stripe-cli:latest
    command: >
      listen
        --forward-to ${HOST_BASE_URL}/webhooks/payment
        --events checkout.session.completed,customer.subscription.created,customer.subscription.updated,customer.subscription.deleted,invoice.paid,invoice.payment_failed
    environment:
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: